apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bootc-image-builder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bootc-image-builder
    app.kubernetes.io/part-of: bootc-image-builder
  name: bootc-image-builder
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: bootc-image-builder
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: bootc-image-builder
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/bootc-image-builder/bootc-image-builder@sha256:335891d230f40a2aba41678d0fc3e81b6e6db1edf22ae5ebb22e4380f6169820
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
