apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bootc-image-builder
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/bootc-image-builder/bootc-image-builder@sha256:90ed357ad9203b120c33f93b82b957d259852f50e3b58823cf24b6f8da4b8ae9
        name: container-image
        resources: {}
status: {}
