apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bootc-image-builder
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhel-bootc-tenant/bootc-image-builder/bootc-image-builder@sha256:ebfc493062609383161a392af4f202944f76bcacb8a2cbd117fab16239c62ac4
        name: container-image
        resources: {}
status: {}
